[theme]

# Primary accent for interactive elements
primaryColor = "#CB4646"

# Background color for the main content area
backgroundColor = "#CB4646"

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = "#FAFAFA"

# Color used for almost all text
textColor = "#EE6C4D"

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"